apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: arclytics
type: Opaque
data:
  secret_key: ZDhjOGYwY2IzMmVkYjkxNDYxNDIwMGQwN2RlOTYwNTI2MmFkNjkwMWZkZGE2NTdmNWU3YjA4MThiMDcxODZhOWVhNmVlZmVmY2YwNGVjMzg3MGQzM2RkY2YzM2Y1MDVhNzM0ODg4MzczMmUzZThmNjY1YzllNzM2NzcyYzViZGQ=
  elastic_apm_secret_token: MzIyYWY1OWNlMTgwOWMxNTI4MmM0ZjdjYWY3YzQ3ZmFlZjFlMjZmYjZjNzg3NDdj
  security_password_salt: QVJDTFlUSUNTLUFOU1RPLVVPVw==
  mongo_root_user: YW5zdG9fYXJjbHl0aWNzX21vbmdvX2FkbWlu
  mongo_root_password: R2RYS3VOaE5OU2pwaHZXMERoSklPUVd0SkNRVGxyc1Z1NURWM1l3VERLZjZwamdpUVpvQ0tBVGx3Z216a1ptdlI1d0J5NXA4WERrT1NtcGg=
  mongo_app_db: YXJjbHl0aWNz
  mongo_app_user: YW5zdG9fYXJjbHl0aWNzX25ldXJhbGRldg==
  mongo_app_user_password: dVMyWG9UOENYcG5zQVNvZGNNOWtjU3p3a1pyR2h3QkhUdkozUlNVYQ==
  redis_port: NjM3OQ==
  redis_password: Q0hPUG1COFBkWjZ5dVNjVllXNEZ1bDhkRkdGR0xOQnJXS21Vcm1jcUFRaU5oZUxuamNvelkxZkVRam5HTlVaVQ==
  mail_server: c210cC5nbWFpbC5jb20=
  mail_username: YWRtaW5AbmV1cmFsZGV2Lmlv
  mail_password: b252c3luaGRjbWZieGRydw==
  elastic_user: ZWxhc3RpYw==
  elastic_password: Kyp6ZTkkLEpNPns7ejlKM1g=
  mapbox_token: c2suZXlKMUlqb2lZMjlrWlc1cGJtcGhOVFVpTENKaElqb2lZMnN4WkcxMU4zWTBNREJ1YmpOcmJ6SXhhbll5ZDJkdGVTSjkuLVdUVjVxZDFsN2pPTDNpX2w4X2VDQQ==
