apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: arclytics
  labels:
    app: web-https
    component: client
spec:
  type: NodePort
  selector:
    app: web-https
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-https
  namespace: arclytics
  labels:
    app: web-https
    component: website
spec:
  selector:
    matchLabels:
      app: web-https
  replicas: 1
  template:
    metadata:
      labels:
        app: web-https
        component: website
    spec:
      containers:
      - name: web-https-container
        image: asia.gcr.io/arc-sim-testing/arc_sim_website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
              - cat
              - /etc/nginx/healthy
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - cat
              - /etc/nginx/healthy
          initialDelaySeconds: 15
          periodSeconds: 60
